{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Functions"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On this lab we will put to practice some of the concepts we have learned on this past few days.\n",
    "\n",
    "`NOTE: On this lab you should try to write all the functions yourself using only the most basic of python syntax and without functions such as len, count, sum, max, min, in, etc. Give it a try. 🧑🏻‍💻👩🏻‍💻`\n",
    "\n",
    "The cell after each exercise contains a few tests to check if your function works as expected."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "from mod.testing import *\n",
    "import unittest"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Write a function that returns the greater of two numbers"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def greater(a,b):\n",
    "    if a > b:\n",
    "        return a\n",
    "    else:\n",
    "        return b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "......................................................................................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.125s\n",
      "\n",
      "OK\n",
      ".................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.125s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(greater)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "#your code here"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Now write a function that returns the largest element on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "65"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def largest(lst):\n",
    "      i n laregets t\n",
    "largest([1,2,3,45,5,5,54,65,3,5,-3])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE\n",
      "EEEEEEEE\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.543s\n",
      "\n",
      "FAILED (errors=100)\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "======================================================================\n",
      "ERROR: runTest (mod.testing.test_greater.<locals>.TestKnown.runTest)\n",
      "----------------------------------------------------------------------\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Monitor 16\\pite_ironhack_labs\\lab-functions-en\\mod\\testing.py\", line 17, in runTest\n",
      "    self.assertEqual(fn(*self.input), self.output, f\"Should be {self.output}\")\n",
      "                     ~~^^^^^^^^^^^^^\n",
      "TypeError: largest() takes 1 positional argument but 2 were given\n",
      "\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.543s\n",
      "\n",
      "FAILED (errors=100)\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_greater(largest)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Write a function that sums all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "16"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def sum_all(lst):\n",
    "    total = 0\n",
    "    for num in lst:\n",
    "        total += num\n",
    "    return total\n",
    "sum_all([3,5,2,6])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.151s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_sum(sum_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Write another function that multiplies all the elements on a list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 85,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "1440"
      ]
     },
     "execution_count": 85,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def mult_all(lst):\n",
    "    total = 1\n",
    "    for num in lst:\n",
    "        total *= num\n",
    "    return total\n",
    "mult_all([3,4,5,6,4])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 86,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.131s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mult(mult_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Now combine those two ideas and write a function that receives a list and either \"+\" or \"*\" and outputs acordingly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 87,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "712080"
      ]
     },
     "execution_count": 87,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def oper_all(arr, oper = \"\"):\n",
    "    if oper == \"*\":\n",
    "        total = 1\n",
    "        for num in arr:\n",
    "            total *= num\n",
    "        return total\n",
    "    elif oper == \"+\":\n",
    "        total = 0\n",
    "        for num in arr:\n",
    "            total += num\n",
    "        return total\n",
    "        \n",
    "oper_all([3,2,5,6,43,23,4], \"*\")\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.126s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_operations(oper_all)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Write a function that returns the factorial of a number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "720"
      ]
     },
     "execution_count": 89,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def factorial(n):\n",
    "    result = 1\n",
    "    for i in range(1, n+1):\n",
    "        result *= i\n",
    "    return result\n",
    "factorial(6)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 90,
   "metadata": {},
   "outputs": [],
   "source": [
    "#factorial formula\n",
    "#n! = n * ( n - 1 ) *...*1\n",
    "\n",
    "# This code defines a function called \"factorial\" which takes an input \"n\". The function uses a for loop to iterate through the range of numbers \n",
    "# from 1 to n+1. For each number in that range, it multiplies the current value of x by the number in the range. At the end of the loop, \n",
    "# the function returns the final value of x, which will be the factorial of the input number \"n\".\n",
    "\n",
    "# The Factorial of a positive integer n is the product of all positive integers less than or equal to n. \n",
    "# For example, the factorial of 6 (written \"6!\") is 6 * 5 * 4 * 3 * 2 * 1 = 720.\n",
    "\n",
    "# So this function takes an input of any positive integer, and returns the factorial of that number."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.191s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_factorial(factorial)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 7. Write a function that takes a list and returns a list of the unique values.\n",
    "\n",
    "`NOTE: You cannot use set. 🤔`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 92,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[1, 2, 3, 4, 5]"
      ]
     },
     "execution_count": 92,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def unique(lst_un):\n",
    "    uniqs = []\n",
    "    for element in lst_un:\n",
    "        found = False\n",
    "        for u in uniqs:\n",
    "            if u == element:\n",
    "                found = True\n",
    "                break\n",
    "        if not found:\n",
    "            uniqs.append(element)\n",
    "    return uniqs\n",
    "\n",
    "unique([1,2,3,2,3,2,3,2,3,4,5,3,5,3,2])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 93,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      ".."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "..................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.446s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_unique(unique)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 8. Write a function that returns the mode of a list, i.e.: the element that appears the most times.\n",
    "`NOTE: You should not use count... 🧐`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 94,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "4"
      ]
     },
     "execution_count": 94,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def mode_counter(arr):\n",
    "    counts = {\n",
    "    }\n",
    "    for elemento in arr:\n",
    "        if elemento in counts:\n",
    "            counts[elemento] += 1\n",
    "        else:\n",
    "            counts[elemento] = 1\n",
    "\n",
    "    largest = 0\n",
    "    key_largest = 0\n",
    "    for key in counts:\n",
    "        if counts[key] > largest:\n",
    "            largest = counts[key]\n",
    "            key_largest = key\n",
    "    return key_largest\n",
    "            \n",
    "            \n",
    "            \n",
    "mode_counter([1,2,3,34,4,3,4,4,65,4,5,6,7,8,4,5,4])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 95,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.145s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_mode(mode_counter)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 9. Write a function that calculates the standard deviation of a list.\n",
    "`NOTE: Do not use any libraries or already built functions. 😉`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 102,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "18.982322603637613"
      ]
     },
     "execution_count": 102,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def st_dev(list_sd):\n",
    "    many = 0\n",
    "    count = 0\n",
    "    for n in list_sd:\n",
    "        count += n\n",
    "        many += 1\n",
    "    mean = count / many\n",
    "\n",
    "    difference_mean = 0\n",
    "    for value in list_sd:\n",
    "        difference_mean += (value - mean) ** 2\n",
    "    variance = difference_mean / (many - 1)\n",
    "    std_value = variance ** 0.5\n",
    "    return std_value\n",
    "\n",
    "st_dev([1,3,4,5,32,4,5,5,6,34,34,5,5,3,6,64,34,4,56,5,3])\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 103,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      ".."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "..................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.153s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_stdev(st_dev)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 10. Write a function to check if a string is a pangram, i.e.: if it contains all the letters of the alphabet at least once. Mind that the strings may contain characters that are not letters."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 104,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 104,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def pangram(string):\n",
    "    abecedary = \"abcdefghijklmnopqrstuvwxyz\"\n",
    "    abecedary_mayus = \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n",
    "    letters = []\n",
    "   \n",
    "     # iter through all the string and append the letters to a list called letters\n",
    "    \n",
    "    for letter in string:\n",
    "        if letter in abecedary:\n",
    "            letters.append(letter)\n",
    "        elif letter in abecedary_mayus:\n",
    "            idx = 0\n",
    "            for i in abecedary_mayus:\n",
    "                if i == letter:\n",
    "                    break\n",
    "                else:\n",
    "                    idx += 1\n",
    "            letters.append(abecedary[idx])          \n",
    "     # Itera through all abecedary letters, if abecedary letter in the list letters, then true, else, false\n",
    "    for abc in abecedary:\n",
    "        encontrada = False\n",
    "        for letra in letters:\n",
    "            if letra == abc:\n",
    "                encontrada = True\n",
    "                break\n",
    "    # if encontradas still false, return false\n",
    "        if encontrada == False:\n",
    "            return False\n",
    "    return True\n",
    "    \n",
    "        \n",
    "            \n",
    "            \n",
    "            \n",
    "          \n",
    "            \n",
    "pangram(\"abcdefghijKlmnopqrstuvwxyZZZ\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "..............................\n",
      "----------------------------------------------------------------------\n",
      "Ran 30 tests in 0.049s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pangram(pangram)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 106,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "' la, me, no, que, soporto, verdad,yo'"
      ]
     },
     "execution_count": 106,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def sort_alpha(string):\n",
    "    words = \"\"\n",
    "    words2 = []\n",
    "    for letter in string:\n",
    "        if letter != \",\":\n",
    "            words += letter\n",
    "        elif letter == \",\":\n",
    "            words2.append(words)\n",
    "            words = \"\"\n",
    "    if words != \"\":\n",
    "           words2.append(words)\n",
    "    words2 = sorted(words2)\n",
    "    \n",
    "    resultado = \"\"\n",
    "    primera = True\n",
    "    \n",
    "    for palabra in words2:    \n",
    "        if  primera == True:\n",
    "            resultado += palabra\n",
    "            primera = False\n",
    "        else:\n",
    "            resultado += \",\" + palabra\n",
    "            \n",
    "    return resultado        \n",
    "            \n",
    "sort_alpha(\"yo, la, verdad, que, no, me, soporto\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 107,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.168s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_alpha(sort_alpha)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 12. Write a function to check if a given password is strong (at least 8 characters, at least one lower case, at least one upper case, at least one number and at least one special character). It should output True if strong and False if not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 108,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "True"
      ]
     },
     "execution_count": 108,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "def check_pass(password):\n",
    "    \n",
    "    tiene_minus = False\n",
    "    tiene_mayus = False\n",
    "    tiene_special = False\n",
    "    tiene_numero = False\n",
    "    tiene_8 = False\n",
    "        \n",
    "    minus = \"abcdefghijklmopqrstuvwxyz\"\n",
    "    mayus = \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"\n",
    "    numero = \"1234567890\"\n",
    "    special = \"!#$%&'()*+,-./:;<=>?@[]^_`{|}~\"\n",
    "\n",
    "    contador = 0\n",
    "    \n",
    "    for char in password:\n",
    "        contador += 1\n",
    "        if char in minus:\n",
    "            tiene_minus = True\n",
    "        if char in mayus:\n",
    "            tiene_mayus = True\n",
    "        if char in numero:\n",
    "            tiene_numero = True\n",
    "        if char in special:\n",
    "            tiene_special = True\n",
    "        if contador >= 8:\n",
    "            tiene_8 = True\n",
    "    if tiene_minus and tiene_mayus and tiene_numero and tiene_8 and tiene_special:\n",
    "        return True\n",
    "    else:\n",
    "        return False\n",
    "\n",
    "check_pass(\"fn}6&iIz\")\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "....................................................................................................\n",
      "----------------------------------------------------------------------\n",
      "Ran 100 tests in 0.160s\n",
      "\n",
      "OK\n"
     ]
    }
   ],
   "source": [
    "# This will test your function \n",
    "test_pass(check_pass)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
